import math

DOOM_RES = DOOM_W, DOOM_H = 320,200

SCALE = 4.0
WIN_RES = WIDTH, HEIGHT = int(DOOM_W*SCALE), int(DOOM_H*SCALE)

H_WIDTH, H_HEIGHT = WIDTH // 2, HEIGHT // 2

FOV = 90
H_FOV = FOV // 2

PLAYER_SPEED = 0.3
PLAYER_ROT_SPEED = 0.12
PLAYER_HEIGHT = 41
PLAYER_SIZE = 3
PLAYER_CLIMB_SPEED = 0.2
PLAYER_FALL_SPEED = 0.3
PLAYER_STEP_AMPLITUDE = 10
PLAYER_STEP_FREQUENCY = 0.01

SCREEN_DIST = H_WIDTH / math.tan(math.radians(H_FOV))
COLOUR_KEY = (152, 0, 136)

MOUSE_SENSITIVITY = 0.03
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT