from enum import Enum
import math

DOOM_RES = DOOM_W, DOOM_H = 320,200

SCALE = 4.0
WIN_RES = WIDTH, HEIGHT = int(DOOM_W*SCALE), int(DOOM_H*SCALE)

H_WIDTH, H_HEIGHT = WIDTH // 2, HEIGHT // 2

FOV = 90
H_FOV = FOV // 2

PLAYER_SPEED = 0.3
PLAYER_ROT_SPEED = 0.12
PLAYER_HEIGHT = 41
PLAYER_SIZE = 16
PLAYER_CLIMB_SPEED = 0.2
PLAYER_FALL_SPEED = 0.3
PLAYER_STEP_AMPLITUDE = 10
PLAYER_STEP_FREQUENCY = 0.01

WEAPON_CHANGE_SPEED = 0.1

SCREEN_DIST = H_WIDTH / math.tan(math.radians(H_FOV))
COLOUR_KEY = (152, 0, 136)

MOUSE_SENSITIVITY = 0.03
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

# can we pass through a portal wall?
MIN_ROOM_HEIGHT = 60
MAX_STEP_HEIGHT = 20

class WALL_TYPE(Enum):
    SOLID_WALL = 0
    DOOR = 1
    PASSABLE = 2
    IMPASSABLE = 3

# for sound effects
SAMPLE_RATE = 11025

# sprites
WEAPON_SPRITES = {
    '1' : 'PISTA0',
    '2' : 'SHTGA0',
}