import pygame as pg

GLOBAL_EVENT = pg.USEREVENT + 0
TEXT_EVENT = pg.USEREVENT + 1
TEXT_FINISH_EVENT = pg.USEREVENT + 2
CONVERSATION_START_EVENT = pg.USEREVENT + 3
CONVERSATION_NEXT_EVENT = pg.USEREVENT + 4
CONVERSATION_END_EVENT = pg.USEREVENT + 5
NPC_RESPONSE_EVENT = pg.USEREVENT + 6
DOOMGUY_FACE_CHANGE_EVENT = pg.USEREVENT + 7
